service: gpt-bot
frameworkVersion: '3'

useDotenv: true

package:
  excludeDevDependencies: true

custom:
  tables:
    messages: 'messages-${sls:stage}'
    payments: 'payments-${sls:stage}'
    sessions: 'sessions-${sls:stage}'
    telegramRequests: 'telegram-requests-${sls:stage}'
    users: 'users-${sls:stage}'
  gpt:
    timeout: 300

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [MessagesTable, Arn]
            - Fn::GetAtt: [PaymentsTable, Arn]
            - Fn::GetAtt: [TelegramRequestsTable, Arn]
            - Fn::GetAtt: [SessionsTable, Arn]
            - Fn::GetAtt: [UsersTable, Arn]
  environment:
    MESSAGES_TABLE: ${self:custom.tables.messages}
    PAYMENTS_TABLE: ${self:custom.tables.payments}
    SESSIONS_TABLE: ${self:custom.tables.sessions}
    TELEGRAM_REQUESTS_TABLE: ${self:custom.tables.telegramRequests}
    USERS_TABLE: ${self:custom.tables.users}
    GPT_TIMEOUT: ${self:custom.gpt.timeout}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  api:
    handler: src/functions/api.handler
    events:
      - httpApi: "*"
  bot:
    handler: src/functions/bot.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [TelegramRequestsTable, StreamArn]
    timeout: ${self:custom.gpt.timeout}

resources:
  Resources:
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.messages}
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.payments}
    SessionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.sessions}
    TelegramRequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.telegramRequests}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.users}
