service: gpt-bot
frameworkVersion: '3'

useDotenv: true

package:
  excludeDevDependencies: true

custom:
  tables:
    telegramRequests: 'telegram-requests-${sls:stage}'
  gpt:
    timeout: 60

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TelegramRequestsTable, Arn]
  environment:
    TELEGRAM_REQUESTS_TABLE: ${self:custom.tables.telegramRequests}
    GPT_TIMEOUT: ${self:custom.gpt.timeout}

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin

functions:
  api:
    handler: src/functions/api.handler
    events:
      - httpApi: "*"
  bot:
    handler: src/functions/bot.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: [TelegramRequestsTable, StreamArn]
    timeout: ${self:custom.gpt.timeout}

resources:
  Resources:
    TelegramRequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tables.telegramRequests}
        StreamSpecification:
          StreamViewType: NEW_IMAGE
