{
  service: "aws",
  frameworkVersion: "3",

  useDotenv: true,

  package: {
    excludeDevDependencies: true
  },

  provider: {
    name: "aws",
    runtime: "nodejs16.x"
  },

  plugins: [
    "serverless-plugin-typescript",
    "serverless-dotenv-plugin"
  ],

  functions: {
    gpt: {
      name: "gpt",
      handler: "main.gpt",
      events: [
        {
            httpApi: {
                path: "/telegraf",
                method: "post"
            }
        }
      ],
      timeout: 29
    }
  }
}
